/* n1519lib_dlmalloc.c
A modified dlmalloc implementation of the N1519 proposal for the C programming language
(C) 2010 Niall Douglas http://www.nedproductions.biz/


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include "../n1519lib.h"
#include <string.h>
#include <errno.h>
#include <malloc.h>

#define ONLY_MSPACES 1
#include "malloc.c.h"
static mspace syspool;

static void init_syspool(void)
{
  ensure_initialization();
  ACQUIRE_MALLOC_GLOBAL_LOCK();
  if(!syspool)
  {
    if(!(syspool=create_mspace(0, 1))) abort();
  }
  RELEASE_MALLOC_GLOBAL_LOCK();
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_aligned_alloc(size_t alignment, size_t size)
{
  if(!syspool) init_syspool();
  return mspace_malloc2(syspool, size, alignment, 0, 0);
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_aligned_realloc(void *ptr, size_t alignment, size_t size)
{
  if(!syspool) init_syspool();
  return mspace_realloc2(syspool, ptr, size, alignment, 0, 0);
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void **n1519_batch_alloc1(int *errnos, void **ptrs, size_t *RESTRICT count, size_t *RESTRICT size, size_t alignment, size_t reserve, uintmax_t flags)
{
  int n;
  size_t maxn=*count, _count=0;
  if(!ptrs && !(ptrs=(void **) n1519_calloc(maxn, sizeof(void *))))
  {
    *count=0;
    return NULL;
  }
  if(!size || !(*size))
  {
    for(n=0; n<(int) maxn; n++)
    {
      if(ptrs[n])
      {
        mspace_free2(syspool, ptrs[n], (unsigned) flags);
        ptrs[n]=0;
      }
      _count++;
    }
  }
  else
  {
    size_t _size;
    {
      void *temp=mspace_malloc2(syspool, *size, alignment, reserve, (unsigned) flags);
      *size=_size=mspace_usable_size(temp);
      mspace_free2(syspool, temp, (unsigned) flags);
    }
    for(n=0; n<(int) maxn; n++)
    {
      void *temp=0;
      if(ptrs[n]) /* resize */
      {
        if(!(flags & M2_PREVENT_MOVE))
          temp=mspace_realloc2(syspool, ptrs[n], _size, alignment, reserve, (unsigned) flags);
      }
      else /* allocate */
      {
        temp=mspace_malloc2(syspool, _size, alignment, reserve, (unsigned) flags);
      }
      if(temp) /* success */
      {
        ptrs[n]=temp;
        if(errnos) errnos[n]=0;
        _count++;
      }
      else /* failure */
      {
        if(errnos) errnos[n]=(ptrs[n] && (flags & M2_PREVENT_MOVE)) ? ENOSPC : ENOMEM;
      }
    }
  }
  *count=_count;
  return ptrs;
}

_Bool n1519_batch_alloc2(int *errnos, struct n1519_mallocation2 **RESTRICT mdataptrs, size_t *RESTRICT count, size_t alignment, size_t reserve, uintmax_t flags)
{
  int n;
  size_t maxn=*count, _count=0;
  for(n=0; n<(int) maxn; n++)
  {
    if(!mdataptrs[n] || !mdataptrs[n]->size) /* free */
    {
      if(mdataptrs[n] && mdataptrs[n]->ptr)
      {
        mspace_free2(syspool, mdataptrs[n]->ptr, (unsigned) flags);
        mdataptrs[n]->ptr=0;
      }
      _count++;
    }
    else
    {
      void *temp=0;
      if(mdataptrs[n]->ptr) /* resize */
      {
        if(!(flags & M2_PREVENT_MOVE))
          temp=mspace_realloc2(syspool, mdataptrs[n]->ptr, mdataptrs[n]->size, alignment, reserve, (unsigned) flags);
      }
      else /* allocate */
      {
        temp=mspace_malloc2(syspool, mdataptrs[n]->size, alignment, reserve, (unsigned) flags);
      }
      if(temp) /* success */
      {
        mdataptrs[n]->ptr=temp;
        mdataptrs[n]->size=mspace_usable_size(temp);
        if(errnos) errnos[n]=0;
        _count++;
      }
      else /* failure */
      {
        if(errnos) errnos[n]=(mdataptrs[n]->ptr && (flags & M2_PREVENT_MOVE)) ? ENOSPC : ENOMEM;
      }
    }
  }
  *count=_count;
  return _count==maxn;
}

_Bool n1519_batch_alloc5(int *errnos, struct n1519_mallocation5 **RESTRICT mdataptrs, size_t *RESTRICT count)
{
  int n;
  size_t maxn=*count, _count=0;
  for(n=0; n<(int) maxn; n++)
  {
    if(!mdataptrs[n] || !mdataptrs[n]->size) /* free */
    {
      if(mdataptrs[n] && mdataptrs[n]->ptr)
      {
        mspace_free2(syspool, mdataptrs[n]->ptr, (unsigned) mdataptrs[n]->flags);
        mdataptrs[n]->ptr=0;
      }
      _count++;
    }
    else
    {
      void *temp=0;
      if(mdataptrs[n]->ptr) /* resize */
      {
        if(!(mdataptrs[n]->flags & M2_PREVENT_MOVE))
          temp=mspace_realloc2(syspool, mdataptrs[n]->ptr, mdataptrs[n]->size, mdataptrs[n]->alignment, mdataptrs[n]->reserve, (unsigned) mdataptrs[n]->flags);
      }
      else /* allocate */
      {
        temp=mspace_malloc2(syspool, mdataptrs[n]->size, mdataptrs[n]->alignment, mdataptrs[n]->reserve, (unsigned) mdataptrs[n]->flags);
      }
      if(temp) /* success */
      {
        mdataptrs[n]->ptr=temp;
        mdataptrs[n]->size=mspace_usable_size(temp);
        if(errnos) errnos[n]=0;
        _count++;
      }
      else /* failure */
      {
        if(errnos) errnos[n]=(mdataptrs[n]->ptr && (mdataptrs[n]->flags & M2_PREVENT_MOVE)) ? ENOSPC : ENOMEM;
      }
    }
  }
  *count=_count;
  return _count==maxn;
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_calloc(size_t nmemb, size_t size)
{
  if(!syspool) init_syspool();
  return mspace_malloc2(syspool, nmemb*size, 0, 0, M2_ZERO_MEMORY);
}

void n1519_free(void *ptr)
{
  if(!syspool) init_syspool();
  mspace_free2(syspool, ptr, 0);
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_malloc(size_t size)
{
  if(!syspool) init_syspool();
  return mspace_malloc2(syspool, size, 0, 0, 0);
}

size_t n1519_malloc_usable_size(void *ptr)
{
  return mspace_usable_size(ptr);
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_realloc(void *ptr, size_t size)
{
  if(!syspool) init_syspool();
  return mspace_realloc2(syspool, ptr, size, 0, 0, 0);
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_try_aligned_realloc(void *ptr, size_t alignment, size_t size)
{
  if(!syspool) init_syspool();
  return mspace_realloc2(syspool, ptr, size, alignment, 0, M2_PREVENT_MOVE);
}

N1519MALLOCNOALIASATTR N1519MALLOCPTRATTR void *n1519_try_realloc(void *ptr, size_t size)
{
  if(!syspool) init_syspool();
  return mspace_realloc2(syspool, ptr, size, 0, 0, M2_PREVENT_MOVE);
}


