/* pthread_permit.h
Declares and defines the proposed C1X semaphore object
(C) 2011-2012 Niall Douglas http://www.nedproductions.biz/


Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef PTHREAD_PERMIT_H
#define PTHREAD_PERMIT_H
#include "pthread_permit1.h"

#ifdef __cplusplus
extern "C" {
#endif

/*! Define the pthread_permit_t type */
typedef struct pthread_permit_s pthread_permit_t;


/*! Creates a permit with initial state. */
inline int pthread_permit_init(pthread_permit_t *permit, _Bool waitersDontConsume, _Bool initial);

/*! Destroys a permit */
inline void pthread_permit_destroy(pthread_permit_t *permit);

/*! Grants permit to all currently waiting threads. If there is no waiting thread, permits the next waiting thread. */
inline int pthread_permit_grant(pthread_permitX_t permit);

/*! Revoke any outstanding permit, causing any subsequent waiters to wait. */
inline void pthread_permit_revoke(pthread_permit_t *permit);

/*! Waits for permit to become available, atomically unlocking the specified mutex when waiting.
If mtx is NULL, never sleeps instead looping forever waiting for permit. */
inline int pthread_permit_wait(pthread_permit_t *permit, pthread_mutex_t *mtx);

/*! Waits for a time for a permit to become available, atomically unlocking the specified mutex when waiting.
If mtx is NULL, never sleeps instead looping forever waiting for permit. If ts is NULL,
returns immediately instead of waiting.

Returns: 0: success; EINVAL: bad permit, mutex or timespec; ETIMEDOUT: the time period specified by ts expired.
*/
inline int pthread_permit_timedwait(pthread_permit_t *permit, pthread_mutex_t *mtx, const struct timespec *ts);





typedef struct pthread_permit_s
{ /* NOTE: KEEP THIS HEADER THE SAME AS pthread_permit1_t */
  volatile unsigned magic;            /* Used to ensure this structure is valid */
  atomic_uint permit;                 /* =0 no permit, =1 yes permit */
  atomic_uint waiters, waited;        /* Keeps track of when a thread waits and wakes */
  cnd_t cond;                         /* Wakes anything waiting for a permit */

  /* Extensions from pthread_permit1_t type */
  int replacePermit;                  /* What to replace the permit with when consumed */
  atomic_uint lockWake;               /* Used to exclude new wakers if and only if waiters don't consume */
} pthread_permit_t;


int pthread_permit_init(pthread_permit_t *permit, _Bool waitersDontConsume, _Bool initial)
{
  permit->permit=initial;
  permit->waiters=permit->waited=0;
  if(thrd_success!=cnd_init(&permit->cond)) return thrd_error;
  permit->replacePermit=waitersDontConsume;
  permit->lockWake=0;
  permit->magic=*(const unsigned *)"PPER";
  return thrd_success;
}

void pthread_permit_destroy(pthread_permit_t *permit)
{
  if(*(const unsigned *)"PPER"!=permit->magic) return;
  /* Mark this object as invalid for further use */
  permit->magic=0;
  permit->replacePermit=1;
  permit->permit=1;
  cnd_destroy(&permit->cond);
}

int pthread_permit_grant(pthread_permitX_t _permit)
{ // If permits aren't consumed, prevent any new waiters or granters
  pthread_permit_t *permit=(pthread_permit_t *) _permit;
  int ret=thrd_success;
  if(*(const unsigned *)"PPER"!=permit->magic) return thrd_error;
  if(permit->replacePermit)
  {
    unsigned expected;
    while((expected=0, !atomic_compare_exchange_weak_explicit(&permit->lockWake, &expected, 1, memory_order_relaxed, memory_order_relaxed)))
    {
      //if(1==cpus) thrd_yield();
    }
  }
  // Grant permit
  atomic_store_explicit(&permit->permit, 1, memory_order_seq_cst);
  // Are there waiters on the permit?
  if(atomic_load_explicit(&permit->waiters, memory_order_relaxed)!=atomic_load_explicit(&permit->waited, memory_order_relaxed))
  { // There are indeed waiters. If waiters don't consume permits, release everything
    if(permit->replacePermit)
    { // Loop waking until nothing is waiting
      do
      {
        if(thrd_success!=cnd_broadcast(&permit->cond))
        {
          ret=thrd_error;
          goto exit;
        }
        //if(1==cpus) thrd_yield();
      } while(atomic_load_explicit(&permit->waiters, memory_order_relaxed)!=atomic_load_explicit(&permit->waited, memory_order_relaxed));
    }
    else
    { // Loop waking until at least one thread takes the permit
      while(atomic_load_explicit(&permit->permit, memory_order_relaxed))
      {
        if(thrd_success!=cnd_signal(&permit->cond))
        {
          ret=thrd_error;
          goto exit;
        }
        //if(1==cpus) thrd_yield();
      }
    }
  }
exit:
  // If permits aren't consumed, granting has completed, so permit new waiters and granters
  if(permit->replacePermit)
    permit->lockWake=0;
  return ret;
}

void pthread_permit_revoke(pthread_permit_t *permit)
{
  if(*(const unsigned *)"PPER"!=permit->magic) return;
  atomic_store_explicit(&permit->permit, 0, memory_order_relaxed);
}

int pthread_permit_wait(pthread_permit_t *permit, pthread_mutex_t *mtx)
{
  int ret=thrd_success;
  unsigned expected;
  if(*(const unsigned *)"PPER"!=permit->magic) return thrd_error;
  // If permits aren't consumed, if a permit is executing then wait here
  if(permit->replacePermit)
  {
    while(atomic_load_explicit(&permit->lockWake, memory_order_acquire))
    {
      //if(1==cpus) thrd_yield();
    }
  }
  // Increment the monotonic count to indicate we have entered a wait
  atomic_fetch_add_explicit(&permit->waiters, 1, memory_order_acquire);
  // Fetch me a permit, excluding all other threads if replacePermit is zero
  while((expected=1, !atomic_compare_exchange_weak_explicit(&permit->permit, &expected, permit->replacePermit, memory_order_relaxed, memory_order_relaxed)))
  { // Permit is not granted, so wait if we have a mutex
    if(mtx)
    {
      if(thrd_success!=cnd_wait(&permit->cond, mtx)) ret=thrd_error;
    }
    else thrd_yield();
  }
  // Increment the monotonic count to indicate we have exited a wait
  atomic_fetch_add_explicit(&permit->waited, 1, memory_order_relaxed);
  return ret;
}

int pthread_permit_timedwait(pthread_permit_t *permit, pthread_mutex_t *mtx, struct timespec *ts)
{
  int ret=thrd_success;
  unsigned expected;
  struct timespec now;
  if(*(const unsigned *)"PPER"!=permit->magic) return thrd_error;
  // If permits aren't consumed, if a permit is executing then wait here
  if(permit->replacePermit)
  {
    while(atomic_load_explicit(&permit->lockWake, memory_order_acquire))
    {
      //if(1==cpus) thrd_yield();
    }
  }
  // Increment the monotonic count to indicate we have entered a wait
  atomic_fetch_add_explicit(&permit->waiters, 1, memory_order_acquire);
  // Fetch me a permit, excluding all other threads if replacePermit is zero
  while((expected=1, !atomic_compare_exchange_weak_explicit(&permit->permit, &expected, permit->replacePermit, memory_order_relaxed, memory_order_relaxed)))
  { // Permit is not granted, so wait if we have a mutex
    if(!ts) { ret=thrd_timeout; break; }
    else
    {
      timespec_get(&now, TIME_UTC);
      long long diff=timespec_diff(ts, &now);
      if(diff<=0) { ret=thrd_timeout; break; }
    }
    if(mtx)
    {
      if(thrd_success!=cnd_timedwait(&permit->cond, mtx, ts)) { ret=thrd_error; break; }
    }
    else thrd_yield();
  }
  // Increment the monotonic count to indicate we have exited a wait
  atomic_fetch_add_explicit(&permit->waited, 1, memory_order_relaxed);
  return ret;
}


#ifdef __cplusplus
}
#endif

#endif
